CREATE UNIQUE INDEX CVEIndex USING BTREE ON CVE(CVE);
CREATE UNIQUE INDEX CVEGroundedTheoryIndex USING BTREE ON CVEGroundedTheory(CVE);
CREATE INDEX FilepathIndex USING BTREE ON Filepaths(Filepath);
CREATE INDEX GitLogCommit USING BTREE ON GitLog(Commit);
CREATE INDEX GitLogFilesCommitFilepath USING BTREE ON GitLogFiles(Commit, Filepath);
CREATE INDEX GitLogFilesCommit USING BTREE ON GitLogFiles(Commit);
CREATE INDEX GitLogFilesFilepath USING BTREE ON GitLogFiles(Filepath);

OPTIMIZE TABLE SVNLog;
OPTIMIZE TABLE SVNLogFiles;
OPTIMIZE TABLE Filepaths;
OPTIMIZE TABLE CVE;
OPTIMIZE TABLE CVESVNFix;
OPTIMIZE TABLE CVEGroundedTheory;
OPTIMIZE TABLE GitLog;
OPTIMIZE TABLE GitLogFiles;