CREATE UNIQUE INDEX CVEIndex USING BTREE ON CVE(CVE);
CREATE UNIQUE INDEX CVEGroundedTheoryIndex USING BTREE ON CVEGroundedTheory(CVE);
CREATE INDEX CVENonSVNFixIndex USING BTREE ON CVENonSVNFix(CVE);
CREATE INDEX FilepathIndex USING BTREE ON Filepaths(Filepath);
CREATE INDEX GitBlameFilepath USING BTREE ON GitBlames(Filepath);
CREATE INDEX GitBlameRevision USING BTREE ON GitBlames(Revision);
CREATE INDEX GitBlameFilepathRevision USING BTREE ON GitBlames(Filepath,Revision);
CREATE INDEX GitBlameFilepathRevisionLineNumber USING BTREE ON GitBlames(Filepath,Revision,LineNumber);

OPTIMIZE TABLE SVNLog;
OPTIMIZE TABLE SVNLogFiles;
OPTIMIZE TABLE Filepaths;
OPTIMIZE TABLE CVE;
OPTIMIZE TABLE CVESVNFix;
OPTIMIZE TABLE CVENonSVNFix;
OPTIMIZE TABLE CVEGroundedTheory;
OPTIMIZE TABLE GitBlames;
OPTIMIZE TABLE GitDiffHunks;